### ISSUE TITLE
Indexing issue (error on line 207ish of graph_gen)

### ISSUE THREAD

**Issue by JE-BT** [redhair-demon/eu4-generator#9]
Hi.

Great code you've got here. I had to fix one issue to get it to run. Error is on line 207ish of graph_gen:

    groups = {f"{names[i]}_{typ}": {
        'name': f"{names[i]}_{typ}", 
        'xy': center([xy for k, xy in enumerate(coords.values()) if clusters[k]==i]), 
        'in': set([n for ii, n in enumerate(nodes) if clusters[ii]==i]),
        'type': 'SEA' if is_sea else 'PROV',
        'adj': set()
        } for i in range(n_clusters)}

Issue is that the way you generate names sometimes doesn't give you enough names to meet n_clusters range. Quick fix is to regenerate names to match limit: 

    if len(names)<n_clusters:
           print(f"Number of Names: {len(names)}, Number of Clusters: {n_clusters}, Fixing...")
           names = gn.generate_names(n_clusters)

This probably creates some issues in how these groups are generated from a world-building perspective, but it gets the code to run. And it isn't common enough to worry about really. Might want to go back through and check that though.

**Comment by redhair-demon** [comment]
Hi,

Could you please provide map base which caused a problem when generated names wasnt enough for clusters? I have pushed some changes and hope this isnt a problem anymore, but its better to check.

**Comment by JE-BT** [comment]
Sure. Here is the file that gave me the error
[RandomMap.zip](https://github.com/redhair-demon/eu4-generator/files/15355864/RandomMap.zip)

**Comment by redhair-demon** [comment]
Oh, I know this map pretty well, have tested first versions with it.
For now, it seems like problem is fixed with current dev version. Thanks for feedback, I appreciate it!
